version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
    open-pull-requests-limit: 0
    assignees:
      - "barsoomx"
    open-pull-requests-limit: 20
    rebase-strategy: auto
